algo: MultiCriticsPPOAgent
n_steps: 1000
batch_size: 256 # 1260
value_coeff: 0.6
entropy_coeff:
  start: 0.01
  end: 0.001
  steps: 1000
clip_eps: 0.20
gamma: 0.95
lr: 0.0003
entry_coeff: 0
kappa: 2.0
beta: 1.0
regulation: 3.0
gae_lam: 0.95
