fname: new_daily_settlement_without_kl_fixed_alpha
agent_class: MultiCriticsPPOAgent
env: EpisodicStreamEnv
timeseries_network: CTTS
multi_critics: True
train_epoch: 10
print_step_log_in: 100
print_episode_log_in: 1
print_env_log_in: 30
save_interval: 10
log_on: true
timer_on: true
earlystop_on: true
checkpoint_on: true
visualization_on: true
seed: 42
